# Generated by Django 5.0.1 on 2024-01-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_history',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='app_sistema_cadastro.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app_sistema_cadastro.product'),
        ),
    ]
