version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: databaseuser
      POSTGRES_PASSWORD: test123

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: sistema_cadastro.settings
      DATABASE_URL: postgres://databaseuser:test123@db:5432/database

volumes:
  postgres_data:
